version: '3.8'

services:
  backend:
    build:
      context: ./spring-boot-server
      dockerfile: Dockerfile
    image: backend:latest
    ports:
      - "8081:8081"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://localhost:5432/mydatabase
      SPRING_DATASOURCE_USERNAME: myuser
      SPRING_DATASOURCE_PASSWORD: mypassword
    depends_on:
      - database

  frontend:
    build:
      context: ./angular-14-client
    image: frontend:latest
    ports:
      - "80:80"
    depends_on:
      - backend

  database:
    image: postgres:15
    container_name: postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: mydatabase
      POSTGRES_USER: USERADMIN
      POSTGRES_PASSWORD: USERPASSWORD
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
